#ifndef COMBINATIONOFGIVENSUM_GLOBAL_H
#define COMBINATIONOFGIVENSUM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMBINATIONOFGIVENSUM_LIBRARY)
#  define COMBINATIONOFGIVENSUMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMBINATIONOFGIVENSUMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMBINATIONOFGIVENSUM_GLOBAL_H
