#ifndef COUNTINGBITS_GLOBAL_H
#define COUNTINGBITS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COUNTINGBITS_LIBRARY)
#  define COUNTINGBITSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COUNTINGBITSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COUNTINGBITS_GLOBAL_H
